using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using api.Models;
using api.Services;

namespace api.Controllers
{
    [Route("api/[controller]")]
    [ApiController]    
    public class SetupController : ControllerBase
    {
        readonly BlogContext _context;

        static Author Kriss = new Author
        {
                AuthorId = 1,
                Name = "Kristaps",
                Description = "Hi, my name is Kristaps"
        };

        static Post Post = new Post 
        {
            PostId = 1,
            Title = "Example post",
            Summary = "This is an example post",
            Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
            AuthorId = Kriss.AuthorId,
            Author = Kriss,
            Tags = new string[]
            {
                "example",
                "post"
            }
        };
        
        public SetupController(BlogContext context)
        {
            _context = context;
        }

        // GET api/values
        [HttpGet]
        public ActionResult<string> Get()
        {
            // _context.Authors.Add(Kriss);
            // _context.BlogPosts.Add(Post);
            if (!_context.Authors.Any())
            {
                _context.Authors.Add(Kriss);
                _context.Posts.Add(Post);

                _context.SaveChanges();
            }


            if (_context.Authors.Any())
                return $"There's an author there: {_context.Authors.First().Name}";

            return "No author there...";
        }
    }
}